name: Deploy to S3

on:
  push:
    branches: [ main ]  # Trigger on pushes to the main branch
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest  # You can choose a different runner

    steps:
      - uses: actions/checkout@v3  # Checkout code from your repository

      - name: Configure AWS credentials  # Add AWS credentials securely
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-south-1  # Update with your region
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set region $AWS_DEFAULT_REGION

      - name: Build your website  # Replace with your build command
        run: npm run build  # Example for a Node.js project

      - name: Sync website to S3  # Upload the built content to S3 bucket
        run: aws s3 sync dist s3://vishnuverse.xyz  # Replace with your bucket namex
